### ISSUE TITLE
appget list

### ISSUE THREAD

**Issue by sbrow** [appget/appget#12]
It would be very useful to be able to list all installed packages. As far as I can tell, the only way to know if a program on your computer is being recognized by appget is to manually `appget search <package name>`, or do `appget outdated` which won't show up to date packages.

P.S. Love that appget recognizes programs retroactively, it's super useful. Keep up the good work! :)

**Comment by sbrow** [comment]
Thanks for the heads up! `appget outdated -v` works for me. :)

**Comment by matthiasg** [comment]
Generally is there a way to get a list as a file and re-install the same list on another machine ? If it had this I would use appget on all my dev machines

**Comment by kayone** [comment]
@matthiasg take a look at https://github.com/appget/appget/issues/11

At its base it's something trivial to do, we already know the list of apps installed on your machine, storing it and reading it back is simple, what gets complicated is installing them in a row, and how to deal with restarts or installers that block because "another installer has requested restart".

**Comment by kayone** [comment]
Getting a list of packages is now implemented using `appget list`

https://docs.appget.net/commands/#list

**Comment by kayone** [comment]
@matthiasg I'm closing this since the `list` function has been implemented. I'm opening a separate issue for the re-install use case #12
