### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by chaehni** [appget/appget#16]
I tried updating WhatsApp using `appget update whatsapp`. Afterwards the version was still the same and appget still reports it as outdated.

**Comment by kayone** [comment]
what version of WhatsApp does appget think you have installed?  could you paste the WhatsApp row from the output of outdated command?

**Comment by chaehni** [comment]
I already updated it manually. However, the vesion was `0.3.1475`. Update was `0.3.1649`.

**Comment by kayone** [comment]
that's strange since the current version available in appget is the latest version https://appget.net/packages/i/whatsapp

**Comment by chaehni** [comment]
I found another example:
```
PS C:\WINDOWS\system32> appget update-all -s
Getting list of available updates...

Total Applications: 8   Updates Available: 1

Installing update 1 of 1

Getting package etcher:latest
Beginning installation of 'etcher'

Downloading installer from https://github.com/balena-io/etcher/releases/download/v1.4.8/balenaEtcher-Setup-1.4.8-x64.exe
   ████████████████████ 100%: 67 MB / 67 MB

Checksum verification PASSED
Updating balenaEtcher to 1.4.8. Currently Installed: 1.4.4
Waiting for installation to complete ...
Installation completed successfully for 'etcher'

Updates Applied Successfully: 1   Updates failed to apply: 0
```
Afterwards, I get this output:

```
PS C:\WINDOWS\system32> appget outdated -v
Starting command [outdated]
Getting list of installed application
Getting list of available updates...
Found 0.6.22 AppGet releases

Total Applications: 8   Updates Available: 1

1 Available Updates:

| Name                        | Package ID | Installed Version | Available Version |
|-----------------------------|------------|-------------------|-------------------|
| Etcher  (only current user) | etcher     | 1.4.4             | 1.4.8             |
```

**Comment by kayone** [comment]
ok, so I figured it out, 

![image](https://user-images.githubusercontent.com/412280/49493047-72dbb780-f80f-11e8-9b98-4165cc882f49.png)

Etcher doesn't upgrade itself properly after they renamed the app. It just installs itself side-by-side which kind of breaks update since doing an update isn't really doing an update.

there is also another issue on ourside which is causing appget not to detect the 1.4.8 being installed. that's something I have to look into, but I suspect should be fairly trivial to fix.
