### ISSUE TITLE
Node 10.x not found

### ISSUE THREAD

**Issue by fvilers** [appget/appget#19]
Hi! It looks like AppGet has manifests for Node 10.x (https://github.com/appget/appget.packages/tree/master/manifests/node) but they can't be found. On the website (https://appget.net/packages/i/node), the latest one is 9.9.0.0 and using the search command from the CLI:

```Found 50 package(s)

| ID   | Name    | Version  | Tag    |
|------|---------|----------|--------|
| node | Node.js | 9.9.0.0  | 9.9.0  |
| node | Node.js | 9.8.0.0  | 9.8.0  |
| node | Node.js | 9.7.1.0  | 9.7.1  |
| node | Node.js | 9.7.0.0  | 9.7.0  |
| node | Node.js | 9.6.1.0  | 9.6.1  |
| node | Node.js | 9.6.0.0  | 9.6.0  |
| node | Node.js | 9.5.0.0  | 9.5.0  |
| node | Node.js | 9.4.0.0  | 9.4.0  |
| node | Node.js | 9.3.0.0  | 9.3.0  |
| node | Node.js | 9.2.1.0  | 9.2.1  |
| node | Node.js | 9.2.0.0  | 9.2.0  |
| node | Node.js | 9.11.2.0 | 9.11.2 |
| node | Node.js | 9.11.1.0 | 9.11.1 |
| node | Node.js | 9.10.1.0 | 9.10.1 |
| node | Node.js | 9.10.0.0 | 9.10.0 |
| node | Node.js | 9.1.0.0  | 9.1.0  |
| node | Node.js | 9.0.0    | 9.0.0  |
| node | Node.js | 8.9.4    | 8.9.4  |
| node | Node.js | 8.8.1.0  | 8.8.1  |
| node | Node.js | 8.8.0.0  | 8.8.0  |
| node | Node.js | 8.7.0.0  | 8.7.0  |
| node | Node.js | 8.6.0.0  | 8.6.0  |
| node | Node.js | 8.5.0.0  | 8.5.0  |
| node | Node.js | 8.4.0.0  | 8.4.0  |
| node | Node.js | 8.3.0.0  | 8.3.0  |
| node | Node.js | 8.2.1.0  | 8.2.1  |
| node | Node.js | 8.2.0.0  | 8.2.0  |
| node | Node.js | 8.1.4.0  | 8.1.4  |
| node | Node.js | 8.1.3.0  | 8.1.3  |
| node | Node.js | 8.1.2.0  | 8.1.2  |
| node | Node.js | 8.1.1.0  | 8.1.1  |
| node | Node.js | 8.1.0.0  | 8.1.0  |
| node | Node.js | 8.0.0    | 8.0.0  |
| node | Node.js | 7.9.0.0  | 7.9.0  |
| node | Node.js | 7.8.0.0  | 7.8.0  |
| node | Node.js | 7.7.4.0  | 7.7.4  |
| node | Node.js | 7.7.3.0  | 7.7.3  |
| node | Node.js | 7.7.2.0  | 7.7.2  |
| node | Node.js | 7.7.1.0  | 7.7.1  |
| node | Node.js | 7.7.0.0  | 7.7.0  |
| node | Node.js | 7.6.0.0  | 7.6.0  |
| node | Node.js | 7.5.0.0  | 7.5.0  |
| node | Node.js | 7.4.0.0  | 7.4.0  |
| node | Node.js | 7.3.0.0  | 7.3.0  |
| node | Node.js | 7.2.1.0  | 7.2.1  |
| node | Node.js | 7.2.0.0  | 7.2.0  |
| node | Node.js | 7.10.1.0 | 7.10.1 |
| node | Node.js | 7.10.0.0 | 7.10.0 |
| node | Node.js | 7.1.0.0  | 7.1.0  |
| node | Node.js | 7.0.0    | 7.0.0  |
```

**Comment by kayone** [comment]
Thanks for filing this, this has led me down a path to fix a bunch of different issues. None of which were the fact that some Node versions were actually missing (they aren't, but they might appear to be on the surface).

#### LTS/General Releases:
Node uses two release channels, [LTS and Current](https://github.com/nodejs/Release#release-plan). Even version releases (8.x, 10.x, etc.) are LTS and odd numbered released (7.x, 9.x, 11.x, etc.) releases are Current.

Previously when we were detecting Node releases from  https://nodejs.org/en/download/releases/ we used the LTS column to detect an LTS release. But as you can see that not exactly accurate. I'll reach out to the Node team to see if they can clarify. That's why we had some 10.x and 8.x releases under `node` package ID. These will be moved in the coming days where all even number releases will be under `node-lts` and all odd numbered releases will be under `node`

#### Dumb Sorting:
Our version sorting was dumb. The sorting algorithm we used for showing the latest releases was not smart enough to realize 10.x is greater than 8.x since one starts with 1 and the other starts with 8. This was fixed yesterday so we now sort versions accurately.

#### 50 is not enough:
Up until yesterday, our search result was limited to 50. Which seems enough for most cases, but it becomes an issue where we have over 100 different version of Node in the repo. so we fixed that were we show an unlimited number of search results.

eg. https://gist.github.com/kayone/670f9281435cef977e8831062d070852

**Comment by fvilers** [comment]
Thanks for the explanation!

**Comment by kayone** [comment]
everything should be fixed now including moving all 6.x, 8.x and 10.x releases moving under `node-lts`
