### ISSUE TITLE
Potential scaling issues in repository layout

### ISSUE THREAD

**Issue by albertdev** [appget/appget#24]
Hi,

First of all, my apologies for the wall of text below.

I was getting fed up with Chocolatey's outdated packages which is how I found [your Medium article about AppGet](https://medium.com/@keivan/appget-what-chocolatey-wasnt-61f2b658d95b). So far it looks like you are on to something good, but I want to warn you about something which I have seen happen several times: people start a new repository format and everything is simple and good. It gets popular, and only then it is realized that the format doesn't scale, either because naming conflicts pop up or because the repository becomes hard to navigate because directories contain too much items (and thus slow navigating the packages folder), not to say that it becomes hard to search (Github for example limits the directory display to 1000 entries - any more and it will say that it couldn't list X items).

It seems like this could happen here as well: as far as I understand it [632 (and counting) packages sit in the manifests folder](https://github.com/appget/appget.packages/tree/master/manifests), and this number can only grow. Chocolatey seems to be at 6 446 distinct packages now, although that likely includes "meta" packages where you can choose between a zip extract or the real installer.

There have been several different solutions I have seen so far:

* The case I'm most familiar with due to being a former Java dev: Apache Maven (a Java package manager) started with a concept called "groups" in which a bunch of packages from the author could be stored. However, due to a lack of guidance people created a new group for each new package (even if it was from the same author) which meant that the root directory of the repository got overloaded. They chose to replace groups with a more hierarchical directory structure based on the DNS domain name owned by the author: `maven/` became `org/apache/maven/`, some package with a website on Github became `io/github/username/`. This decreased the rate of growth in directory indexes enough that it has remained workable to this day.
* Closer to home we get the Linux package managers. Here I have seen several different mechanisms, although they also rely on segregating packages:
    * Arch Linux uses a flat namespace similar to AppGet. However, even there we can see that they actually split their packages across several repositories: they have got `Core`, `Extra`, `Community`, `Testing`. Also, I guess they keep their repository size down simply by maintaining only "a few" hand-picked packages because the [user-submitted packages are not kept in a repository](https://aur.archlinux.org/) at all. That obviously sidesteps the problem completely because less packages means less overhead.
    * Gentoo has a hierarchical directory structure based on the type of app. You can see this in the [Gentoo ebuild repository](https://github.com/gentoo-mirror/gentoo). While the folder name or 'app type' is usually optional when installing packages, you must specify it in case of collisions.
    * Debian (and Ubuntu) have a flat namespace, but their repository is structured around the [first character of the package name](http://ftp.us.debian.org/debian/pool/main/) with a special exception for the rather common `lib` prefix, and they then use [an index file](http://ftp.us.debian.org/debian/dists/stable/main/binary-amd64/) which holds the available package names + the combinations of dependency versions which got tested.

Obviously, switching to a new layout _has_ downsides:

* Packages become non-trivial to find by hand, and managing the manifest repository needs a slight bit more care. Then again, [https://appget.net/packages/](https://appget.net/packages/) and the CLI `appget` could be modified to deal with it.
* There will need to be a transitional period in which the existing packages somehow still work while packages get added in the new structure. A few thoughts for solutions though:
    * Either the newer structure is used in a new repository which only a newer version of appget could look at while older versions keep using the old repository URL for a while.
    * If the current version of `appget` has a forwards compatibility mode where extra keys in the manifest don't trigger an error then existing package folders could keep existing but receive a `moved: "app/foobar"` key in their manifest to indicate it's an old-style package. The package index can thus be built in a newer `appget` by excluding all the manifests which contain the `moved` key. Of course, I don't know how the current `appget` reacts if it finds a folder without a manifest and instead contains subdirectories with manifests. To reduce problems it might be necessary to publish a version of `appget` which fails gracefully in such a scenario before any package gets added in the new directories.

~~A few of the above solutions hinge on whether `appget` is able to update itself, or at least warns that a newer version is available. I don't know if this has been foreseen yet (I believe chocolatey has a way to do it), but it might in itself be worth investigating.~~

(EDIT: I have since learned that appget has no problems updating itself. Also, it doesn't interact with the repository directly but connects to a REST API, so the format of the git repository might not matter _that_ much.)

----
Oh yes, and as a closing note on breaking compatibility [some words from the late Dennis Ritchie](http://www.lysator.liu.se/c/dmr-on-or.html) on why `&` and `==` work non-intuitively in the C language:

> ... it seemed safer just to split & and && without moving & past an existing operator.  (After all, we had several hundred kilobytes of source code, and maybe 3 installations....) 

Breaking compatibility might be tough now, but imagine how impossible it becomes the longer one waits...

Anyway, thank you if you have made it so far through this post, hopefully it was interesting.

**Comment by gitjeff2** [comment]
I was was thinking through a bug report on this exact issue the other day. I'm using `AppGet` to maintain a small number of systems now myself. I second @albertdev here. I was thinking of BSD ports, Gentoo Portage, and Ubuntu and how they approach this exact problem. I think I have something to add to this conversation.

To find fault is easy and to do better is hard. You've got a good start here. I have a few basic ideas that might help:

Package ID name collisions on a project of this magnitude are *going* to happen. So, it's worth thinking about ways to mitigate that. Some ideas I've come up with:

* Use a more stringent naming convention for the package ID. There is an amazingly detailed naming convention defined by [TOSEC](https://www.tosecdev.org/tosec-naming-convention) that might be helpful here. Something similar would help disambiguate similar packages. The downside is package ID's would tend to be longer and more difficult to remember.
* A mandatory record version number field, akin to DNS record serial number, in the AppGet YAML file. This would be helpful when two identical records exist (same package name, same package version) but the package behaves differently perhaps due to different switches being present or some other factor. This would also help if an admin is locally overriding one package with another by hand.

I agree with @albertdev's idea of splitting the repo into several sub-repos that are very well maintained. The best I can come up with is:

| Directory             | Purpose                                                                                             |
| ---------------------- | -----------------------------------------------------------------------------------------|
| `core`                   | The name of the "core repo" itself, whatever you decide to call it.  |
| `/apps`                  | A high level dir for all apps.                                                             |
| `/apps/*foo*`         | Every app gets put in a logical directory by type, *e.g., `/office`.     |
| `/development`    | All runtimes and programming languages go here.                          |
| `/games`               | A high level entry for games.                                                           |
| `/games/*foo*`      | Games in the *foo* category, *e.g.*, `/rts`.                                       |
| `/os`                     | A high level dir for OS components                                                  |
| `/os/*vendor*`       | Useful if AppGet stands in for WSUS/SCCM or expands beyond MS Windows.|
| `/pkg`                   | Everything related to the `appget` package manager itself.           |
| `/sysadmin`          | Sysinternals, 7-zip, and similar utilities go here.                            |
| `/vm`                     | A high level entry for hypervisors and emulators.                          |
| `/vm/*sys*`            | Whatever system being emulated, *e.g,* `/pc` or `/snes`              |

I think that every repository section should be subdivided, too. It might make sense to divide entries into directories by `#,A–Z`. That might be overkill though, so `/app/office/[vendor]/` be less annoying to navigate manually. In that case, we would need a `foss` directory as a stand-in vendor for minor open source projects that don't have a major backer. The more I think about it, the more I prefer the vendor approach. Either way, this should keep the items per directory relatively low.

## How Should Core Be Maintained?
* There should be a "one package one product rule."
* It should be the unaltered vendor provided original installer. This way the vendor can't use AppGet as a scapegoat and not support a given install even thought it is valid.
* It should come from the original vendor's site or a mirror the vendor designates as trusted.
* As minor upgrades come out YAML manifests should just be updated with the latest version.

## How Should The Legacy Repository Be Maintained?
* Manifests for EOL products should go here. This implies the need for a YAML entry that specifies EOL date.
* Major updates 1.*x* to 2.*x* updates should be captured here whenever possible.
* Whenever a major feature is dropped or added it should be treated as a major update *e.g.*, "last version to support MS Windows 7", etc. even if the version number isn't indicative of a major release.
* The manifest should point to the original software vendor's official download for as long as possible.
* If that's not possible, a reasonably trustworthy source such as <http://www.oldversion.com/> should be used.

## How Should The Community Repository Be Maintained?
* Products that would be problematic to keep in the core repository go here.
* Reasons might include software patents (e.g., *[lame MP3 encoder*](http://lame.sourceforge.net/)) or a touchy EULA issue.
* Alternate installers go here, too! 
* So, if a product only comes as a ZIP or an EXE from the vendor but someone in the community has built a very flexible MSI version the product should go here.
* In general we should enforce a "one package one product" rule here too. The installer that is the most flexible by having the most options and installing reliably on the widest range of systems should be the winner here.

**Comment by priyadarshan** [comment]
Another very interesting and very solid package manager is [raven](http://www.ravenports.com/), as this post describes it, the long-lasting champion on Repology’s top 10 repositories regarding package freshness](https://eerielinux.wordpress.com/2018/11/30/one-year-of-flying-with-the-raven-ready-for-the-desktop/)

**Comment by albertdev** [comment]
@gitjeff2 I'm not saying the repository needs to be split into several git repositories for it to work, or that everything which is there needs to be shaken up immediately. I opened this issue because I noticed that the official package repository stores all packages inside one big directory. The AppGet documentation even already contains [guidance on package naming](https://docs.appget.net/manifests/#package-id), so I was mostly targeting that "large directory" problem, knowing that at least Windows has trouble navigating through a directory which contains over 5 000 items or more.

After looking at the AppGet source files I've come to realize that AppGet doesn't read the repository directly, instead the AppGet CLI tool simply sends a request with currently installed packages to a REST API (of which I haven't found the sources of yet) which then responds which packages need an update. This might make the directory problem less of an issue as the REST API can do all kinds of caching tricks which the AppGet CLI tool doesn't need to be aware of. Whether the server can handle the load of searching through the entire package repository remains to be seen though, which I believe is why other package managers try to download the entire package repository or its indexes to do the upgrade checks locally.

----

@priyadarshan  It was not my intention to make an exhaustive list of package managers so I'm sure there will be things missing. It's the first time I've heard about Ravenports, and it seems actually one of the weirder systems in that it isn't a package manager for a single operating system. Instead it's rather _meta_, describing high-level build definitions which are then later translated into platform-specific build files and pre-built into several different repositories. What I'm **most interested in** is how the repository is layed out, because my original post above is mostly of how simple directories can grow so big that they put load on the filesystem.

I did some research, and Ravenports seems to do its own unique thing in how it [structures its root directory](https://github.com/jrmarino/ravensource): it has a flat namespace but applications are grouped in folders named after the first two characters of the Package Id's SHA1 hash.

Take for example `vim`. If we calculate the SHA1 hash of those three characters we get `e1a58852a14e3a9968e89097ccb1fc37f2deba01`. Therefore the vim build defintions are stored in a folder named [bucket_E1/vim](https://github.com/jrmarino/ravensource/tree/master/bucket_E1/vim), and this organization helps to keep the number of files in each directory down.

**Comment by kayone** [comment]
I really appreciate the time and effort you guys have put into your detailed comments. Let me provide some context on how things are done behind the scene and why I think this might not be an issue (unless of course, I'm missing something which is absolutely possible).

The GitHub repository at its core is just a system of record. We use GitHub mainly so we can track versions (git history) and review edits (pull-requests).

Neither the app or any of our backend services directly access it to respond to user requests.

Anytime a commit is pushed to master (pull-request has been merged or a direct commit by our update service), a webhook is triggered by GitHub which makes an authenticated call to one of our services called "Octobot"

Octobot then validates the request and makes a request to GitHub to get the content of the manifest that has been changed.

Once the content has been validated for the 2nd time directly from GitHub, it will trigger a system-wide message letting all other services know of an updated package manifest.

One of those services (Nex) will process the request and update our backend package index. All user operations are performed against that high-performance index, that's how we can do a fuzzy search for misspelled or even synonym based searches (eg. gogle chrom). I can promise you that our actual package index which services the client and https://appget.net/packages/ is capable of handling millions of packages without breaking a sweat.

So now that we know, the client won't have any scaling issues lets talk about some of the two other potential areas,

#### Working with the repository locally:
According to [Stackoverflow](https://stackoverflow.com/questions/4944709/windows-limit-on-the-number-of-files-in-a-particular-folder)

Here are the file system limits on how many items you can have in a folder,

FAT/FAT16: 512
FAT32: 65,534
NTFS: 4,294,967,295

So unless you are running on FAT16 which is very unlikely (Max disk size of 4GB) then you should be fine.


#### Browsing through GitHub:
I think this is a pretty okay tradeoff to make to leave the rest of the system more intuitive (shorter package names, less categorization etc) and that 1000 limit is something that GitHub could and might change in the future.



I hope this clears things a bit, let me know if you think there are still areas we should be concerned with or if you have any questions or need more clearfification on anything.

**Comment by gitjeff2** [comment]
> @gitjeff2 I'm not saying the repository needs to be split into several git repositories for it to work, or that everything which is there needs to be shaken up immediately.

@albertdev, sorry. I wasn't trying to put words in your mouth. I misunderstood your intent.

**Comment by gitjeff2** [comment]
> I really appreciate the time and effort you guys have put into your detailed comments. Let me provide some context on how things are done behind the scene and why I think this might not be an issue (unless of course, I'm missing something which is absolutely possible).

Thanks. This is a very handy tool. The information you gave on the backend of all of this is very helpful. You're right, as long as none of the API's you use start rate-limiting you everything should scale fine.

> #### Working with the repository locally:
> According to [Stackoverflow](https://stackoverflow.com/questions/4944709/windows-limit-on-the-number-of-files-in-a-particular-folder)
> 
> Here are the file system limits on how many items you can have in a folder,
> 
> FAT/FAT16: 512
> FAT32: 65,534
> NTFS: 4,294,967,295
> 
> So unless you are running on FAT16 which is very unlikely (Max disk size of 4GB) then you should be fine.

That's true from a raw file count perspective but there is something that isn't obvious you'll have to consider. A file system is a database of sorts of sorts, the more entries you have in a given directory the harder the file system has to work. I've seen file systems brought to their knees due to large amounts of of small (less than 4kB) files when a user entered the directory via GUI. The effect is less severe in the command-line but still an issue. So, there is that to consider. I'm not saying it has to change right away, but I'm still concerned about scaling.

> I think this is a pretty okay tradeoff to make to leave the rest of the system more intuitive (shorter package names, less categorization etc) and that 1000 limit is something that GitHub could and might change in the future.

For now, it's not bad. You're right, for now there are probably other issues that need to be handled first. Just consider that if `appget` gets popular the growth in terms of installation base and package count could grow very rapidly. 

I meant to bring this up earlier but my post was already long…

In the Linux world there is one package manager that is very much like `appget` in some ways, it's called *portage* and it's primarily driven by the `emerge` command in [Gentoo Linux](https://www.gentoo.org/). Unlike `apt-get` or `yum` which consists of a database that just points to a few HTTPS servers that host packages, everything in portage is a script. Each script, like `appget`'s YAML files, directly downloads source code from the original provider and compiles it at installation time.

So, you could probably take a lot of inspiration from Portage package system and the `emerge` command that runs it. Here is how Gentoo breaks up its packages <https://packages.gentoo.org/categories>. Here is an example `.ebuild` file for the `zip` program: <https://gitweb.gentoo.org/repo/gentoo.git/tree/app-arch/zip/zip-3.0-r3.ebuild>.

**Comment by priyadarshan** [comment]
@gitjeff2 Thank you for the very informative comments, I have learned a lot!

**Comment by albertdev** [comment]
I have also seen large directories "display slowly" well before they hit the posted theoretical limit. It's all in the way that filesystems store directory contents and how GUIs display them.

Of course, if the repository layout doesn't really matter to the client then it could be updated at any point in the future,  And the naming conflicts problem might remain, but the documentation does contain guidelines on how to avoid it in the first place.

Anyway, if I understand the official stance right now it can be summarized as "we'll cross that bridge when we get to it". I don't disagree given the lengthy post from @kayone, therefore I'm closing this issue.

**Comment by bb010g** [comment]
As a note, CPAN handles this for authors by doing a `F/FO/FOOBAR/Acme-Anvil.tar.gz` split. AppGet obviously doesn't have authors, but this is like a more readable version of what Git does with object hashes (`fo/ob/arbaz`).

:+1: to this mostly being about browsability, too. The file system may be able to handle it just fine, but most programs don't expect to be handed 32K files all at once.
