### ISSUE TITLE
Add Schema Version Field to YAML Manifests

### ISSUE THREAD

**Issue by gitjeff2** [appget/appget#32]
As `appget` matures the YAML manifest file will no doubt change. With time, some entries will get renamed and other entries will be added. If there is no `manifestVersion:` key (or similar) it's hard to write third party tools that validate `appget` YAML files. Also, it's harder to know if you've made a mistake if you're writing a YAML manifest by hand once the documentation grows beyond a certain point. Lastly, it's *a lot* easier to write unit tests if you know *exactly* what fields are permitted in what versions of the YAML manifest and don't have work backwards from a given set of entries.

**Comment by kayone** [comment]
We've never added a version because we've never needed one, or maybe we've always had one 😉 

Think of it like this, there is a `ver` filed in the manifest, the current value is `1` which is not written to the file because it's the default value. Think of how we don't write `x86` for installers.

We could add it to the documentation and allow for an explicit `ver: 1` but that seems a bit premature.

I'm open to being persuaded but as it stands I don't think it's really necessary.
