### ISSUE TITLE
How can I help appget to identify the right version of installed app

### ISSUE THREAD

**Issue by ihodev** [appget/appget#39]
E.g. Sublime Text is already has the latest version, but `appget` can't see it

```
| Sublime Text             | sublime-text | 3                 | 3207              |
```

P.S. Thanks for the awesome project ❤️

**Comment by kayone** [comment]
it looks like when sublime text is installed it doesn't register its the correct version.

![image](https://user-images.githubusercontent.com/412280/58434154-18f5d500-806f-11e9-8cd9-37bc99c064a5.png)

The best way to resolve the issue is to contact the author of Sublime Text and ask him/her to update their installer to register the correct version number.

**Comment by ihodev** [comment]
Oh, I see. Thanks!
