### ISSUE TITLE
Privacy concerns with logging

### ISSUE THREAD

**Issue by pcnova** [appget/appget#41]
From looking at the code I noticed it logs some info to appget.net at the end of every install (`InstallerContext.SubmitResult`), plus troubleshooting info sent through Sentry.

Now, I'm not implying anything nefarious is going on - I can see how this info is useful and I see no personal info collected.

However, without visibility into what appget.net is doing, I'm sure you can see how this can be a problem for privacy-minded people. So, my questions are:

- Any plans to make appget.net more transparent, or at least to have a privacy policy?
- Any plans to have the ability to only log locally?
- Can we have more info about the reasons for logging at the end of installs?

Thanks!

**Comment by kayone** [comment]
Sorry about the delayed response, I didn't want to rush it, and it has been busy in the past few days at work,

First of all, I really appreciate you taking the time taking a look over at the source code, 

As you mentioned, we try our best not to collect information unless it's something that can be used to drastically improve support and functionality of AppGet (Making money or profit is not considered).

Not to cover some of the data we collect:

### Privacy Policy
Absolutely, I'll start working on something right away.

### Disable logging
To be honest, the main thing that has been holding this back is we don't have a config infrastructure. I'll add this to our todo list with a high priority because I think it's important.

### Sentry
We use an opensource tool called https://github.com/getsentry/sentry to collect crash data, anytime AppGet crashes or fails to do what a user has requested it to do we send the crash information as well as some context information, e.g. command that was being executed, version of Windows, if the user was an admin or not etc. This has helped us resolved MANY issues that we've only seen in the wild.
I should also note, We host our own instance of sentry as you can see (sentry.appget.net) which means all data is hosted, stored and processed by AppGet. Also, we purge all crash information after 14 days.

### InstallerContext.SubmitResult
This data is useful in two ways,

1. It tells us if a specific package has an installation issue. Maybe we aren't passing the correct arguments, and all installs by appget are failing. If we see a large number of failures for a specific package, we look into it and see if it's something we could resolve.

2. One of the main features of appget is that we can manage app installs by applications that weren't even installed by AppGet, we do this by reading and parsing the Windows installer database.

However, some installers make things hard by not exposing the IDs they will be installed as, see #15. If you look at the data submitted by InstallerContext you'll notice we are sending the Windows Installer Records that are added/removed after an install or uninstall. This allows us to find a pattern and match pretty much all installed application regardless of install method. (eg, 100% of Firefox installs use ID `FIRE_FOX`).

**Comment by pcnova** [comment]
Thanks for the detailed response and your commitment to improve on this. Your reasons for logging also make sense. Keep up the good work! :+1:
